### ISSUE TITLE
after installing the plug-in, click on the page activity to report 500 errors

### ISSUE THREAD

**Issue by peixiaoqing** [momibun926/redmine_issue_evm#103]
redmin：4.0.0
ruby：2.3.8
rails： 5.2.2

Hello, after installing the plug-in, click on the page activity to report 500 errors. See the screenshot, what is the reason?

Here is the error message：

Started GET "/redmine/activity" for 10.10.10.246 at 2019-01-10 14:54:32 +0800
Processing by ActivitiesController#index as HTML
  Current user: admin (id=1)
Completed 500 Internal Server Error in 92ms (ActiveRecord: 10.5ms)
  
NameError (uninitialized constant Evmbaseline):
  
lib/redmine/activity/fetcher.rb:106:in `map'
lib/redmine/activity/fetcher.rb:106:in `constantized_providers'
lib/redmine/activity/fetcher.rb:90:in `block in events'
lib/redmine/activity/fetcher.rb:89:in `each'
lib/redmine/activity/fetcher.rb:89:in `events'
app/controllers/activities_controller.rb:56:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
![1547103232 1](https://user-images.githubusercontent.com/35130532/50951303-974e4200-14e7-11e9-90f6-b15e244a2bf0.jpg)

**Comment by momibun926** [comment]
hi @peixiaoqing 
Thank you for report.
Sorry, no error occurs in my environment.
I hve no idea.

but, It may be worth a try, Please fix the following file.
init.rb
line:11
Redmine::Activity.register 'evmbaseline'
->
Redmine::Activity.register 'Evmbaseline'

models/evmbaseline.rb
line:44
type: 'evmbaseline',
->
type: 'Evmbaseline',
