### ISSUE TITLE
EVMのオプションに親チケット指定、ユーザ指定をすることは可能でしょうか。

### ISSUE THREAD

**Issue by musicman-n4** [momibun926/redmine_issue_evm#104]
現在のEVMグラフのページの下に追加する形で、オプションが別のグラフやサマリー情報を確認したいです。

例１　親チケット指定
１つのプロジェクトの中で色々な機能を作成している場合、プロジェクトをわけず、親チケットを分けカスタムクエリー作成してチケット抽出しています。その抽出条件のEVMを確認したいときに利用したい。

例２　ユーザ指定
各個人の生産性把握に利用したいです。

上記のような事は可能でしょうか。

環境：
Redmine version 3.4.4.stable
Ruby version 2.4.4-p296 (2018-03-28) [x86_64-linux]
Rails version  4.2.8

**Comment by momibun926** [comment]
書き込み頂きありがとうございます。

例１　親チケット指定
プラグインの内部では、チケットを抽出して、計算クラスに渡してEVMを計算するように作られています。親チケットを把握するのは簡単なのですが、子、孫、ひ孫、、、のチケットを抽出する良いアイデアがありません。個人的に実装したかった機能でもあるのですが、先送りにした経緯があります。
少しお時間ください。

例２　ユーザ指定
こちらは、なんとか出来そうな気がしています。
メインページの最下段に、ユーザー毎のpv,ev,ac,sv,cvが表示されればよいてすかね？
最低限欲しいものを教えていただけますでしょうか？

いずれにせよ、ちょっと時間がかかりそうです。

**Comment by musicman-n4** [comment]
ご返信いただきありがとうございます。

* 親チケット指定
出来たら嬉しいなと思ったので、お忙しい中の作業となるかと思いますでお時間あるときで全然大丈夫です。

* ユーザ指定
pv,ev,ac,sv,cv + cpi, spiもあるといいかなと思います。

### 全体のイメージ
オプションに親チケット入力、トラッカー複数選択、ユーザ選択、グラフ表示ON、OFFができるとぐっと分析しやすくなります。

メインページに「追加」みたいなボタンで、新規のEVM設定が設定でき、別オプションのEVMを表示できるといいかなと思います。

メインページの中に以下のように色々出力できると分析や報告、予測が立てやすいです。
パフォーマンス的な問題もあるので、増やしすぎると表示に時間がかかりそうですが・・・。

* Redmineのプロジェクト全体EVM
* プロジェクト中の親チケット10で集約したEVM
* プロジェクト中の親チケット20で集約したEVM
* AユーザのEVM
* BユーザのEVM
* CユーザのEVM

上記でも申しましたが、お忙しい中の作業となるかと思いますでお時間あるときで全然大丈夫です！

**Comment by momibun926** [comment]
早速の返信、詳細なイメージありがとうございます。
まずは、着手しやすそうなユーザー毎のEVMの表示を実装しようかと思います。

1. オプション画面に、ユーザー毎のEVM出力チェックボックスをつける。
2. チェックオンの時に、最下段にユーザー毎のEVMをグラフ無しで表示する。

グラフについては、パフォーマンスとの兼ね合いがあるので、一旦スコープアウトします。
極力ミニマムな実装をして、徐々に拡張していく方針て進めていきます。

参考までに、1プロジェクト内のチケットにアサインしているユーザーは何名ほどですか？

**Comment by musicman-n4** [comment]
ご対応してくださるとのこと、誠に感謝しております。

> 極力ミニマムな実装をして、徐々に拡張していく方針て進めていきます。
トラッカー複数指定だけはあるとありがたいです。
課題トラッカー等、アクティビティに関係のないチケットが混ざるので、数字に意味のあるEVMが出なくなる気が致します。

> 参考までに、1プロジェクト内のチケットにアサインしているユーザーは何名ほどですか？
プロジェクトによりけりにはなってしまいますが、5名～10名です。

**Comment by momibun926** [comment]
ブランチ(develop_user_evm)で開発を始めましたので、時々覗いてみてください。
ユーザーごとのEVM表示はできました。
次は選択したトラッカーでEVMを表示するようにしますが、時間かかると思います。
気長に待っていてください。

**Comment by momibun926** [comment]
すこし時間が取れたので対応しました。
ブランチ(develop_user_evm)の最新版をお使いください。
https://github.com/momibun926/redmine_issue_evm/tree/develop_user_evm

- 担当者ごとのEVM値を表示
- トラッカーを選択してEVM値を表示

試用していただき、問題がないようであれば、Masterにマージします。
ちょっとパフォーマンスが悪くなった気がしますが、グラフを表示しないだけまだ耐えられるかなとも思います。

**Comment by momibun926** [comment]
申し訳ございません。
redmine は3.4.4をお使いでしたね。
私の環境が最新版になっていまして、3.4.4に戻して対応しなければなりませんので、少々お待ちください。結構時間がかかるかもしれません。

**Comment by musicman-n4** [comment]
環境古くて申し訳ありません。
ご対応いただけているだけでも嬉しい限りです。
気長にお待ちしております。

**Comment by momibun926** [comment]
@musicman-n4 
ご無沙汰しています。
3.4.4の環境が作れず、当ISSUEの対応を断念しようと思いますが、問題ありませんでしょうか？
可能であれば、redmineを4.0以上にアップリフトしていただけると嬉しいのですが、、、

**Comment by momibun926** [comment]
@musicman-n4 
ご無沙汰しています。
4.0で対応を行っていた、担当者ごとのEVM値（グラフなし）と選択したトラッカーでのEVM値（グラフなし）を3.4.xに対応させました。
ブランチ"redmine3-4-3"をお使いください。
https://github.com/momibun926/redmine_issue_evm/tree/redmine3-4-3

**Comment by momibun926** [comment]
引き続き親チケット指定でEVMを表示させるようにしました。
ただし、関連する全てのチケットに開始日、予定日が必ず入力されていないと表示ができません。
