### ISSUE TITLE
PVとEVの計算方法について

### ISSUE THREAD

**Issue by sada-ogawa** [momibun926/redmine_issue_evm#107]
質問となりますが以下ご確認いただきたく。

PVの計算方法について
　開始日から期日のうち、営業日で予定工数を割ったものを積み上げているかと思います。
　こちら、例えば日曜日に作業工数を付けた場合も同様でしょうか？
　現在使用させていただいておりますが、週末締め、月曜日集計とした場合に想定外に遅延している結果となる場合が何度か経験しております。
　そのうち、数回は土日に稼働が登録されていたものでもしかするとと思い質問致しました。

EVの計算方法について
　README.mdにおいては、チケット完了後にEVとして計上される説明かと思いますが、
　予定工数*進捗率というような実態に見えました。現在の計算式を教えていただきたく。
　また、このような実態の場合前日、前々日時点のEVはどのようになりますか？
　※進捗率については、最新の物のみ保持しているのでないかと思い質問となります。

**Comment by momibun926** [comment]
お問い合わせありがとうございます。
以下回答です。

PVについて
土日祝日は計算対象外です。
金曜日から月曜日までの期日で、40時間のチケットを作成した場合は、金曜日、月曜日に各々20時間のPVで計算しています。
ただし、チケットの期間が土日祝のみの場合は、営業日としてPVを計算しています。

EVについて
チケットが完了した日付でEVを計上しています。
正直なところ、進捗率の入力がある場合の計算はいまいちで、現時点での進捗率でEVを計上しています。
前日50%、前々日は20%だったとしても、表示をした時点では50%で計算しています。最終的には完了した時点の日付でEVが計上される事になります。
なので、進捗率が入力されているときはあくまでも参考値となります。
当初、進捗率を設定した日付を拾って、より正しくEVを計算しようと思ったのですが、うまく拾えなかった経緯がります。

**Comment by sada-ogawa** [comment]
早速の回答ありがとうございます。

２件とも承知しました。
こちらでもいろいろと実験してみます。
何かありましたら別途質問させていただきます。

**Comment by sada-ogawa** [comment]
早速の回答ありがとうございます。

２件とも承知しました。
こちらでもいろいろと実験してみます。
何かありましたら別途質問させていただきます。

**Comment by momibun926** [comment]
もし、進捗率を考慮しない、休日を考慮しない等のオプション指定が必要であれば、issueを上げていただければ検討したいと思います。
