### ISSUE TITLE
Charts not shown

### ISSUE THREAD

**Issue by mrazek** [momibun926/redmine_issue_evm#124]
Hello,
I have problem with 3-4-3 branch of code. EVM plugin works and shows data till I put any SPent Time value into it with this error in firefox object inspector...
![image](https://user-images.githubusercontent.com/12605987/69543003-ed579700-0f8c-11ea-9116-c5920a2c7c34.png)

Please, any clue, how to solve it?

Many thanks for any advice!

**Comment by momibun926** [comment]
hi @mrazek 
thank you for reporting.
if  entered spent time, chart is shown?
please tell me more details that you entered issues information.
ex. start date, due date, spent time

**Comment by mrazek** [comment]
HI, @momibun926, many thanks for reaction!

If spent time is not entered, charts are shown. once i put one "spent time" record, charts vanish. It seems to me, that it's something like bad conversion from number to string or vice-versa, but I can't say where or why. I am nether ruby nor javascript programmer, bud once i commented out "spent time" series in charts in "drawcharts.js", the appeared again, even if spent time records were recorded (obviously that series was not drawn in the chart).
My configuration is

**Comment by momibun926** [comment]
hi @mrazek 
Thanks for information.
it seems to parent task have "spent time". usually "spent time" on parent issue is sum of child issues.
Probably, this is cause of this issue.
I checked this issue on week end.

**Comment by mrazek** [comment]
Hi, unfortunately, even removing spent and estimated time form parent issue didn't help...
![image](https://user-images.githubusercontent.com/12605987/69829142-30c93400-121f-11ea-833c-2992c44edfc4.png)

**Comment by momibun926** [comment]
hi @mrazek  
database is MySQL or postgre?
calculate amount of spent time is sum function on SQL.
my environment is MySQL.

**Comment by mrazek** [comment]
Unfortunately, I run on Postgress 9.6.15

**Comment by momibun926** [comment]
Hi @mrazek 

Thaank you for respond.
Maybe SQL function (SUM) is not working well on postgre.
Could you correct follows?

now:
` 
  def evm_costs(proj, condition = " 1 = 1 ")
    Issue.cross_project_scope(proj, "descendants").
      select("spent_on, SUM(hours) AS sum_hours").
      where(SQL_COM.to_s).
      where(condition).
      joins(:time_entries).
      group(:spent_on).
      collect {|issue| [issue.spent_on.to_date, issue.sum_hours] }
  end
`
after this
`
  def evm_costs(proj, condition = " 1 = 1 ")
    Issue.cross_project_scope(proj, "descendants").
      where(SQL_COM.to_s).
      where(condition).
      joins(:time_entries).
      group(:spent_on).sum(:hours)
  end
`

**Comment by momibun926** [comment]
hi @mrazek 
I just pushed at branch "redmine3-4-3".
May be fixed.

**Comment by mrazek** [comment]
Unforntunatelly it still seems, that it does not work... I have really busy time nowadays, so I am not able to test it more. hope, that next week or week after I will find some time to do that... Many thanks for all your effort!

**Comment by momibun926** [comment]
HI @mrazek 
Thank you for reporting.
When you have time, it will be helpful if you can get a production log or debug log.

**Comment by momibun926** [comment]
Hi @mrazek 
If there is no additional information, it will be closed. Please reopen if you encounter any problems again.
