### ISSUE TITLE
nil can't be coerced into Float

### ISSUE THREAD

**Issue by ccummings135** [momibun926/redmine_issue_evm#18]
We were missing information on some of our issues and got the following error :
TypeError (nil can't be coerced into Float):
  plugins/redmine_issue_evm/lib/evm_logic.rb:242:in `+'
  plugins/redmine_issue_evm/lib/evm_logic.rb:242:in `block in calculate_earned_value'
  C:in `each'
  C:in `each'

I went in and changed the evm_logic.rb page
On the Math sections I added .to_f to the variables. This turns a nil variable to a float of 0.0
example of one line  
              temp_ev[close_date].nil? ? temp_ev[close_date] = issue.estimated_hours.to_f : temp_ev[close_date] += issue.estimated_hours.to_f

Now it works great. 
when you are working with variables it is best to change them to a float or integer so that you will not get an error message. Just a safety net. 

Other than that the plugin seems to work fine. THANKS!

**Comment by momibun926** [comment]
@ccummings135 Thank you for reporting and valuable suggestion.
Please wait until the corresponding.

**Comment by momibun926** [comment]
Just now,bug fixed.
thanks a lot! ccummings135.
