### ISSUE TITLE
Add EV Calculation on Activities (time tracking)

### ISSUE THREAD

**Issue by abolfazl-khosh** [momibun926/redmine_issue_evm#190]
Hi Hajime,

Please add EV Calculation on Activities (time tracking). Now we can calculate the EV for Version, Assignee, Tracker and Parent issue but can’t calculate for activities. For this you should add Estimate time for any activities on the issue and then can calculate the EV for Activities.

Thanks

**Comment by momibun926** [comment]
@abolfazl-khosh 
Thank you for the request.
Can you provide some more specific examples?

**Comment by momibun926** [comment]
I have investigated the code and it is quite difficult to show EVM in Activity.
