### ISSUE TITLE
Internal Error : NoMethodError in_time_zone

### ISSUE THREAD

**Issue by skalimer0** [momibun926/redmine_issue_evm#192]
Hello,

I use REDMINE 4.1.1 with ruby 2.6.6 and PUMA 5.2.0
and plugin fail to display : "Internal error"
I use :
- Bass hours of day : 8.0
- Exclude holidays and weekend with "fr_m"
- Any calculation method
- All charts wih threshold 0.9 

NoMethodError (undefined method `in_time_zone' for nil:NilClass):

plugins/redmine_issue_evm/lib/calculate_ev.rb:69:in `block in calculate_earned_value'
plugins/redmine_issue_evm/lib/calculate_ev.rb:66:in `each'
plugins/redmine_issue_evm/lib/calculate_ev.rb:66:in `calculate_earned_value'
plugins/redmine_issue_evm/lib/calculate_ev.rb:23:in `initialize'
plugins/redmine_issue_evm/lib/calculate_evm_logic.rb:53:in `new'
plugins/redmine_issue_evm/lib/calculate_evm_logic.rb:53:in `initialize'
plugins/redmine_issue_evm/app/controllers/evms_controller.rb:67:in `new'
plugins/redmine_issue_evm/app/controllers/evms_controller.rb:67:in `create_evm_data'
plugins/redmine_issue_evm/app/controllers/evms_controller.rb:38:in `index'

thanks

**Comment by momibun926** [comment]
@skalimer0
Thank you for your reporting.
We'll investigate this weekend, so please wait a little while.

**Comment by momibun926** [comment]
@skalimer0
What version of rails are you using?

**Comment by skalimer0** [comment]
I'm using rails 5.2.4.2.

**Comment by momibun926** [comment]
Hi, @skalimer0 
I have analyzed the error log.
The cause of the error is that the close date of the closed issue is not set.

I was not able to reproduce the issue in my test environment.
Could you please tell me what kind of tickets are registered in your project?

For example, a parent ticket that has all child tickets completed. etc.

**Comment by skalimer0** [comment]
I have 25000 issues (since 2012) and i need to clean data i think...
I post message after that to said if it's work...

thanks

**Comment by skalimer0** [comment]
So... i update issues to have closed_on value just for closed status.
Now i have this one :

Completed 500 Internal Server Error in 3503ms (ActiveRecord: 130.8ms)

TypeError (nil can't be coerced into Float):

plugins/redmine_issue_evm/lib/chart_data_maker.rb:80:in `/'
plugins/redmine_issue_evm/lib/chart_data_maker.rb:80:in `block in performance_chart_data'
plugins/redmine_issue_evm/lib/chart_data_maker.rb:77:in `performance_chart_data'
plugins/redmine_issue_evm/app/controllers/evms_controller.rb:74:in `create_evm_data'
plugins/redmine_issue_evm/app/controllers/evms_controller.rb:38:in `index'
l

**Comment by momibun926** [comment]
@skalimer0 
Can you tell me version of  this plugin?
You can confirm see init.rb in redmine_issue_evm directory.

I checked Latest source, It seems to concern time entry data.

**Comment by skalimer0** [comment]
I used the lastest version : 5.3.5
All issues don't have time entry (just someone). We use redmine to record all task, all our work. So, our time entry is the time how passed to "in progress" to "closed" (we have also "suspend" status). the system compute the time is external to redmine with also assigned_to field to have individual stats and project stats. the time is divide if we have parallele issues.

No time entry is need to be write by users, If we manage all our task with issues : it's work fine.

I think, we need to push these time data to redmine time entry to use your plugin ?

**Comment by momibun926** [comment]
Hi, @skalimer0 
This plugin is calculation EVM value.
 PV: estimate hours of issue 
 EV: estimate hours of issue on closed date
 AC: time entry

But, I just now understand that you no use time entry.

In my environment, I cannot reproduce the error that occurred.
I have tried not using time entry and it is displayed normally.
However, the reason why the error occurred is that the AC used to display the performance chart is nil.
I will try and fix it. I will contact you later to try.

p.s. I'm using machine translation, so sorry if it's hard to understand.

**Comment by momibun926** [comment]
Hi, @skalimer0 

I just pushed fixed code at master branch.
Can you try to get the latest source and restart redmine?

**Comment by skalimer0** [comment]
Good !!!

It's OK with master branch

Thanks a lot

Now i need to put all time on redmine by autocompute

**Comment by skalimer0** [comment]
i'll write french translation for your plugin soon ;)

**Comment by momibun926** [comment]
Thanks!
