### ISSUE TITLE
Little typo on tables

### ISSUE THREAD

**Issue by soladev** [momibun926/redmine_issue_evm#197]
I've noticed a small typo on the EVM page, where the table column reads "Perfromance" instead of "Performance". In case it's a translation-related issue (which I doubt but we never know), I use Redmine with the "French" language.

![image](https://user-images.githubusercontent.com/16501931/109531354-1502ac80-7ab8-11eb-8eed-2072ad31125b.png)

(It's an awesome project I love it !)

**Comment by momibun926** [comment]
Hi, @soladev 
Thank you for reporting.
I  just merge code.
Could you try latest code on master.

regard,

**Comment by momibun926** [comment]
Some users are in French. (#192)
Could you wait for someone to translate it into French.

**Comment by soladev** [comment]
I confirm it's fixed, thanks ! I'll look forward translations and I'll test them when they will be done
