### ISSUE TITLE
Making EAC evolve over time on graph

### ISSUE THREAD

**Issue by soladev** [momibun926/redmine_issue_evm#203]
Hello,

I was wondering if it would be possible to make the EAC value to be set on each day on the graph. Basically showing on the graph the evolution of the EAC value over the period of the project. 

I think it would be a little enhancement that can help visualize at which point in time users underestimated or overestimated the time taken by issues.

**Comment by momibun926** [comment]
Hi, @soladev 
Thanks for the valuable suggestion.
Showing the EAC value  each day on the graph may be a good thing for project members.
I'll see if I can implement it.

**Comment by momibun926** [comment]
Hi, @soladev
I've just pushed it to branch: 5.4_develop.
Daily EAC is shown on the chart. You can try it if you like.
I shown it on the Project chart, Should I have created a different chart? 
If you have any other requests, please let me know.

**Comment by soladev** [comment]
It seems to be working as expected, thanks ! 
I think it's fine to show it on the Project chart, as it's interesting to compare the Daily EAC value to the BAC for example.
Again thank you very much for this change !
