### ISSUE TITLE
Proposal to implement

### ISSUE THREAD

**Issue by formigadiablo** [momibun926/redmine_issue_evm#231]
As a user of this plugin I think it would be cool to have some sort of summary block that could be displayed in the overview tab.

**Comment by momibun926** [comment]
@formigadiablo 
hanks for the great suggestions.
Does the overview content mean that Metrics, Baseline variance, etc. will be displayed?
Or what do you feel would be useful to have displayed on the OverviewTab?

**Comment by momibun926** [comment]
I was a little mistaken.
Are you suggesting that it would be nice to see the EVM summary on the Overview tab in Redmine?

**Comment by momibun926** [comment]
There are several ways to add to the standard Redmine functionality, but I am not very familiar with them.
I will look into the possibility of implementing this in the next version of the plugin.

Regards,

**Comment by momibun926** [comment]
hi, @formigadiablo 
I have added a simple EVM to the Overview page. Try the master branch if you like!
