### ISSUE TITLE
Representation of PV/EV/AC in monetary units, not only in hours.

### ISSUE THREAD

**Issue by janbkrejci** [momibun926/redmine_issue_evm#236]
Hi, what do you think about this idea?

A task/issue could have some means to express its PV/EV/AC in currency:
- if the task represents human labour, then by adding hourly rate and calculating the cost value
- but the task can also be of another type, not a human labour, i.e. purchasing an asset, leasing a machine etc.

Then, if we are able to calculate cost price of the task, we can:
- express PV, EV and AC as money, instead of hours
- aggregate PV, EV and AC at Project level in custom Project fields (by specifying date of report and re-calculating values of the custom fields). Of course we can do this already, but I think that for reporting purposes, money is better unit than hours.

Thanks in advance for your opinion

**Comment by momibun926** [comment]
hi, @janbkrejci 

I think it is a very great idea.

I think EVM management is a similar way of looking at things in your opinion.
To achieve this in Redmine would be a bit outside of Redmine's purpose though.
I think it would be better to fully customize and package Redmine than to achieve this with a plugin.

**Comment by janbkrejci** [comment]
OK, sounds reasonable, thanks.
