### ISSUE TITLE
Accruing work performed manually to specific dates

### ISSUE THREAD

**Issue by janbkrejci** [momibun926/redmine_issue_evm#237]
Hi, if I understand well, the task completion percentage is saved in real time to some kind of journal when the value is changed.

Therefore it is not possible to manually edit a history of task completion.

This leads to a problem with EV, because I can not say that Task X was 50 % completed a month ago, 80 % a week ago and finished yesterday. As a result, I can not create Project status report for the past dates. And the charts are also somewhat unusable.

My idea is to have a possibility of entering task completion percentage in a similar way as we can enter a time spent on tasks. With dates.

What do you think, would this be even possible?

Thanks for your opinion.

**Comment by momibun926** [comment]
Hi, @janbkrejci

Thank you for your opinion.

In conclusion, it is very difficult for me to implement a solution.

Certainly the JOURNAL records a variety of changes.
When was the completion rate changed, when was the ISSUE closed? etc.

This plugin was created with the intention of reflecting the past STATUS as accurately as possible.
So we expect the issue owner to make changes to RATIO as much as possible on that day.
However, we also understand that there are times when you may want to go back in time to input ratio changes.

**Comment by janbkrejci** [comment]
Hi, thanks for the reply. I understand. Will think about a simple solution, but I have to learn Ruby first :-)
