### ISSUE TITLE
The issue_EVM is not properly accounting for the aggregate value of activities in the sub-projects

### ISSUE THREAD

**Issue by liomoura** [momibun926/redmine_issue_evm#24]
Hello, 

In internal testing on my VM, I created our current project structure:

![image](https://cloud.githubusercontent.com/assets/10420467/7555366/39c37a62-f720-11e4-920e-3c2015e49b0f.png)

In my tests I realized that the EVM Issue work properly in pure redmine, for activities that have estimated the expected date setados, and are within the same project.

![image](https://cloud.githubusercontent.com/assets/10420467/7555346/53417382-f71f-11e4-9d2b-8a3f261161b8.png)

![image](https://cloud.githubusercontent.com/assets/10420467/7555401/9c1dcffa-f720-11e4-9a8a-cf0a5aaad800.png)

Even with activities in 100% completed the EV remains at 0 at issue graphic EVM.

Tests realized by moving activities History and requirement for team project, and the Issue EVM was lost, not returning values correctly.

Sorry, but my english is not very good. I'm from brazil.

**Comment by momibun926** [comment]
hi @liomoura 
Thank you for reporting.
Please wait until the corresponding.

**Comment by liomoura** [comment]
Hello,

News?

Regards

**Comment by momibun926** [comment]
hi @liomoura 
Sorry, It could not be reproduced in my environment.
If possible , I want to know the tickets are registered in each of the project.

**Comment by liomoura** [comment]
Hello @momibun926 

Example...

-> 2015-08 - Master Project (this project are concentrated activities with estimated time)
--> 154882 PhdM - (this project are concentrated activities with estimated time)	
---> Desenvolvimento - (only activities with time spent, because the "estimated time" is disabled)
----> Team Jedi - (only activities with time spent, because the "estimated time" is disabled)

To keep the estimates in parent activities, we apply a patch that allows editing, even if the daughter has estimated, do not know if this change affect the operation of your plugin.

Regards,

**Comment by momibun926** [comment]
Thank you @liomoura 

All ticket is inputted start-date and end-date?
This plugin is require inputted of start-date and end-date.
and supports up to sub-project,sorry.

By improving the method of counting the ticket , it is likely to be met to your needs .
But,Time to correct is likely to take.

**Comment by momibun926** [comment]
hi @liomoura 
Changed to calculate contains ticket of sub-projects.
Can you try ? In the latest version.

**Comment by liomoura** [comment]
Hi @momibun926 

I performed tests on the new version, but appears to me that the chart is displaying only the 'spent time' spent properly.

![image](https://cloud.githubusercontent.com/assets/10420467/9475262/ec9f920a-4b3b-11e5-962f-244fcd7c38ae.png)

My project have the following values:

PV -> 104.0 (estimated time)
AC -> 210.42 (spent time)
EV -> 48% (% done rate)

**Comment by momibun926** [comment]
hi @liomoura 
This plugin is required start-date and end-date.
When the start-date, end date, and estimated time has not been input , EVM value of daily can not be computed.
Does your ticket has been input ?

**Comment by liomoura** [comment]
@momibun926 

Yes, the tickets have 
- start-date
- end-date
- estimated time (parent task)

the calculation takes into account the "total_spent_time" of the activity? because the times are always recorded in activities that do NOT have estimated (in most cases).

**Comment by momibun926** [comment]
hi @liomoura 

Require each ticket value.(exclude parent ticket)

PV -> estimated time(0 or more) , strat-date(not empty) ,end-ate(not empty) 
EV -> Use estimated time of PV. Calculated when done-ratio is in putted or status is complete.
AC -> spent time of ticket(strat-date(not empty) ,end-ate(not empty)) 

Your "How to use" of the ticket that was not expected.

**Comment by liomoura** [comment]
@momibun926 

I concluded the plugin is not working as expected, really the way we use, but thanks for the attention and effort in solving my problem.

You can close this issue.
