### ISSUE TITLE
Question - EVM Report for specific date

### ISSUE THREAD

**Issue by janbkrejci** [momibun926/redmine_issue_evm#240]
Hi again,

what do you think, would it be possible to add a datepicker to EVM Report so that I can calculate and store report values for specific date? For example end of month? If I understand well, currently I am able to create report only for current date.

Thanks for your opinion.

**Comment by momibun926** [comment]
You can create a report with past dates by selecting a past date on the main page and jumping to the report page!

**Comment by janbkrejci** [comment]
Cool! Did not notice. Thanks a lot!

regards

Jan
