### ISSUE TITLE
Division by zero in calculate_evm_logic.rb >> rest_days

### ISSUE THREAD

**Issue by janbkrejci** [momibun926/redmine_issue_evm#242]
Hi,

in rest_days function it happens to me that the parameter spi_value is zero, which leads to division by zero error.

Would it be possible to handle the situation in some way like:

def rest_days(pv_value, ev_value, spi_value, basis_hours)
      if spi_value == 0
        return  ((pv_value - ev_value) / basis_hours).round(0)
      end
      ((pv_value - ev_value) / spi_value / basis_hours).round(0)
end

...does this make sense to you?

Thanks and best regards

Jan

**Comment by momibun926** [comment]
hi,

Thank you for your reporting.

Probably possible.
It may take some time, but I will test and fix the code too.

**Comment by momibun926** [comment]
if spi_value == 0
  ((pv_value - ev_value) / basis_hours).round(0)
else
  ((pv_value - ev_value) / spi_value / basis_hours).round(0)
end

**Comment by janbkrejci** [comment]
Perfect, thanks!
