### ISSUE TITLE
Unable to install on redmine 3.1

### ISSUE THREAD

**Issue by balczezzz** [momibun926/redmine_issue_evm#61]
Hi, 
We have problems activating the plugin on our Redmine 3.1. The tab is visible, but the plugin fails to run.
We have tested this on almost clean Redmine running only DMSF Document Management System Features http://www.redmine.org/plugins/dmsf plugin. The log details are:

Processing by EvmsController#index as HTML
  Parameters: {"project_id"=>"do-testow-redmine"}
  Current user: admin (id=1)
PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ... NULL AND fixed_version_id IS NOT NULL)  ORDER BY effective_...
                                                             ^
: SELECT DISTINCT "issues"."project_id", "issues"."fixed_version_id" FROM "issues" INNER JOIN "projects" ON "projects"."id" = "issues"."project_id" INNER JOIN "versions" ON "versions"."id" = "issues"."fixed_version_id" WHERE ((projects.lft >= 3 AND projects.rgt <= 4)) AND (start_date IS NOT NULL AND due_date IS NOT NULL AND fixed_version_id IS NOT NULL)  ORDER BY effective_date ASC
Completed 500 Internal Server Error in 35ms (ActiveRecord: 8.6ms)

ActiveRecord::StatementInvalid (PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ... NULL AND fixed_version_id IS NOT NULL)  ORDER BY effective_...
                                                             ^
: SELECT DISTINCT "issues"."project_id", "issues"."fixed_version_id" FROM "issues" INNER JOIN "projects" ON "projects"."id" = "issues"."project_id" INNER JOIN "versions" ON "versions"."id" = "issues"."fixed_version_id" WHERE ((projects.lft >= 3 AND projects.rgt <= 4)) AND (start_date IS NOT NULL AND due_date IS NOT NULL AND fixed_version_id IS NOT NULL)  ORDER BY effective_date ASC):

Any ideas on what may cause this?

**Comment by momibun926** [comment]
@balczezzz 
Thank you for reporting.
Please tell me your enviroment. Database is postgreSQL or MySQL?

**Comment by balczezzz** [comment]
Environment:
  Redmine version                3.1.2.stable
  Ruby version                   2.2.0-p0 (2014-12-25) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.5.0
  Filesystem                     
Redmine plugins:
  redmine_dmsf                   1.5.5

**Comment by momibun926** [comment]
thanks.
Please wait for a few days.
I cannot test it,because my enviroment is MySQL, but try to repair a source code.

**Comment by balczezzz** [comment]
Appreciate your rapid replies. Looking forward to receiving your response then.

**Comment by momibun926** [comment]
@balczezzz 
I corrected a source code. Just now pushed.
Would you try the latest DEVLOP branch?

**Comment by balczezzz** [comment]
Great! Works perfectly now! Appreciate your assistance and help!

**Comment by momibun926** [comment]
I was able to solve a problem by your cooperation.
I make new release on this weekend.
Thanks!!!
