### ISSUE TITLE
doesn't work upon adding actual time

### ISSUE THREAD

**Issue by amr-abdelhamid** [momibun926/redmine_issue_evm#64]
The basic scenario doesn't work with latest redmine 3.2.0

**Environement**:

- Windows 7
- redmine 3.2.0
- ruby: ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]
- Rails 4.2.5
- Database: sqlite3

Scenario:

1. add a new project
2. add a feature with estimated time = 100
3. click on EVM, it works great
4. add actual time = 10
5. click on EVM tab, the following error appears:

Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
If you are the Redmine administrator, check your log files for details about the error.

redmine log:
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"5"}
  Current user: admin (id=1)
  Rendered issues/_action_menu.html.erb (3.0ms)
  Rendered issue_relations/_form.html.erb (2.0ms)
  Rendered issues/_relations.html.erb (2.0ms)
  Rendered issues/_action_menu.html.erb (2.0ms)
  Rendered issues/_form_custom_fields.html.erb (0.0ms)
  Rendered issues/_attributes.html.erb (10.0ms)
  Rendered issues/_form.html.erb (17.0ms)
  Rendered attachments/_form.html.erb (2.0ms)
  Rendered issues/_edit.html.erb (27.0ms)
  Rendered issues/_sidebar.html.erb (2.0ms)
  Rendered watchers/_watchers.html.erb (3.0ms)
  Rendered issues/show.html.erb within layouts/base (60.0ms)
Completed 200 OK in 119ms (Views: 71.5ms | ActiveRecord: 18.0ms)
Started GET "/projects/evm/evms" for ::1 at 2016-02-03 12:01:53 +0200
Processing by EvmsController#index as HTML
  Parameters: {"project_id"=>"evm"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 36ms (ActiveRecord: 18.0ms)

ArgumentError (comparison of String with Date failed):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by momibun926** [comment]
@amr-abdelhamid
Thank you for report. 
Please wait for a few days.

**Comment by momibun926** [comment]
@amr-abdelhamid 
This error is to occur when using SQLite3.
I repaired a code, will you try it?
450eb50

**Comment by amr-abdelhamid** [comment]
@momibun926 
I have tested it and it works perfect with SQLite3. 
Thanks!
