### ISSUE TITLE
Baseline settings - question

### ISSUE THREAD

**Issue by balczezzz** [momibun926/redmine_issue_evm#66]
Hi, 
We're setting up the whole company project reporting around your plugin - this just need some proper procedures and policing in place ;) 

Just wanted to know what does the baseline setting do? I presume a _new baseline_ saves the state of **all** issues at a given time in **PV fields**for that particular baseline. Thanks for explaining.

**Comment by momibun926** [comment]
Almost right!
Not all issues,Only issues of inputted start-date and due-date.

**Comment by balczezzz** [comment]
Great, thanks for your reply!
