### ISSUE TITLE
"No data to display"

### ISSUE THREAD

**Issue by amr-abdelhamid** [momibun926/redmine_issue_evm#68]
EVM doesn't display data although the project has Open tasks, closed tasks, with estimated hours, and actual hours reported. 

Please advise!

**Comment by amr-abdelhamid** [comment]
Ok .. I figured out what's the problem. The issue is that we do not enter a due date for the tasks.

The way we work is as follows:
- We define a version (sprint), with a duration of 2 weeks. 
- We assign tasks on this sprint
- We assign estimated effort on tasks
- tasks start and end can be anytime during the sprint time

Sometimes, it is useful to assign a start date, but not a due date. Is there a way to handle this? for example, assign the end date of the sprint to all tasks with no due date?

**Comment by momibun926** [comment]
@amr-abdelhamid 
Nice idea!
I have to modify many code. But try to do.

**Comment by amr-abdelhamid** [comment]
Ok .. great ..

**Comment by adrianobr** [comment]
+1

**Comment by momibun926** [comment]
hi @amr-abdelhamid ,@adrianobr
I tried challenging to add functionality, but I noticed that we needed a lot of code changes.
We abandoned the addition of functions this time.

**Comment by momibun926** [comment]
@amr-abdelhamid 
It was able to use the date of the version as well. Please pull latest master and try.

**Comment by archonwang** [comment]
@momibun926 
unfortunately, I tested it on my environment and it seems not OK

the error information is 

```
Started GET "/projects/sesametranslate/evms" for 10.1.200.167 at 2017-04-07 19:26:45 +0800
Processing by EvmsController#index as HTML
  Parameters: {"project_id"=>"sesametranslate"}
  Current user: hui.wang (id=8)
Completed 500 Internal Server Error in 377ms (ActiveRecord: 25.3ms)

ArgumentError (comparison of Date with nil failed):
  plugins/redmine_issue_evm/lib/evm_logic.rb:409:in `<='
  plugins/redmine_issue_evm/lib/evm_logic.rb:409:in `sort_and_sum_evm_hash'
  plugins/redmine_issue_evm/lib/evm_logic.rb:389:in `calculate_actual_cost'
  plugins/redmine_issue_evm/lib/evm_logic.rb:37:in `initialize'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:58:in `new'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:58:in `block in index'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:53:in `each'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:53:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

ArgumentError (comparison of Date with nil failed):
  plugins/redmine_issue_evm/lib/evm_logic.rb:409:in `<='
  plugins/redmine_issue_evm/lib/evm_logic.rb:409:in `sort_and_sum_evm_hash'
  plugins/redmine_issue_evm/lib/evm_logic.rb:389:in `calculate_actual_cost'
  plugins/redmine_issue_evm/lib/evm_logic.rb:37:in `initialize'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:58:in `new'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:58:in `block in index'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:53:in `each'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:53:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by amr-abdelhamid** [comment]
@momibun926 I'm afraid I'm no longer working for the company which is implementing this process.

**Comment by momibun926** [comment]
@amr-abdelhamid 
If you have the opportunity to use it again, please try it.

**Comment by momibun926** [comment]
@archonwang 
Thank you for trying out.
What kind of environment do you use?

**Comment by archonwang** [comment]
@momibun926 
my environment is

```
Environment:
  Redmine version                3.3.2.stable.16519
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
```

**Comment by momibun926** [comment]
@archonwang 
Direct cause : maxdate is nil.
Root cause : SQL condition.
I pushed master just now.

**Comment by archonwang** [comment]
@momibun926 , Thanks. I have tested it for newest version and it's working well.
