### ISSUE TITLE
What does baseline mean for this plugin?

### ISSUE THREAD

**Issue by edipox** [momibun926/redmine_issue_evm#69]
Hi,
I've been reading about EVM and baseline, but I don't get how baseline works with this plugin. How does it affect the calculation? What does it mean here? How it works?

**Comment by taniadaniela** [comment]
If the baseline is optional, how can PV be based on it?

**Comment by momibun926** [comment]
@edipox
Baseline is like snapshot of plan.
If you don't need snapshot, use option 'don't use baseline'

**Comment by momibun926** [comment]
@taniadaniela
Based on estimate hours of issue.
