### ISSUE TITLE
You can't search inside a project

### ISSUE THREAD

**Issue by djcaesar9114** [momibun926/redmine_issue_evm#71]
When you're at the home of Redmine and click on "search", you can search among EVM, but if you're inside a project (let's say the issue list) and click on "Search", you don't have the "EVM" choice.
Tested on Redmine 3.2.1.stable

**Comment by momibun926** [comment]
I need to add search scope.
refs https://github.com/alexbevi/redmine_knowledgebase/pull/331/commits/378bf0822f407c36d4441b05d3a4e2bb7c6291e1

**Comment by momibun926** [comment]
hi @djcaesar9114 
In case of search of EVM baseline, select "All project" or "My project" on SEARCH window.

**Comment by momibun926** [comment]
root cause is typo.
"type" of event provider.

**Comment by momibun926** [comment]
@djcaesar9114 
Fixed. Please try with the latest master.
