### ISSUE TITLE
opening 500 error. for issue no to_time

### ISSUE THREAD

**Issue by Jiangshan00001** [momibun926/redmine_issue_evm#89]
Started GET "/redmine/projects/abcd/evms" for 192.168.1.188 at 2017-06-07 12:23:09 +0800
Processing by EvmsController#index as HTML
  Parameters: {"project_id"=>"abcd"}
  Current user: test4(id=4)
Completed 500 Internal Server Error in 639ms (ActiveRecord: 224.8ms)

NoMethodError (undefined method `to_time' for nil:NilClass
Did you mean?  to_i):
  plugins/redmine_issue_evm/lib/evm_logic.rb:372:in `block in calculate_earned_value'
  plugins/redmine_issue_evm/lib/evm_logic.rb:369:in `calculate_earned_value'
  plugins/redmine_issue_evm/lib/evm_logic.rb:43:in `initialize'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:42:in `new'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:42:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

I used the plugin. and find the above error.
i have no ruby skill.  could you fix it please?
thanks

**Comment by momibun926** [comment]
Thankyou for report.
Probably because closed date is not set for closed ticket.
I will examine it in detail at the weekend

**Comment by momibun926** [comment]
@Jiangshan00001
Bug fixed.
I pushed at latest master just now.
Please try it.

**Comment by Jiangshan00001** [comment]
thanks, i will try it  as soon as possible

**Comment by Jiangshan00001** [comment]
it works perfect.
I'm sorry that I've forgotten to feed back.
