### ISSUE TITLE
500 error when try to open  evm_graph_version

### ISSUE THREAD

**Issue by Jiangshan00001** [momibun926/redmine_issue_evm#90]
maybe because i have no project version?

  Rendered plugins/redmine_issue_evm/app/views/evms/_explanation.erb (0.3ms)
  Rendered plugins/redmine_issue_evm/app/views/evms/_view_option.erb (1.2ms)
  Rendered plugins/redmine_issue_evm/app/views/evms/_measure.erb (3.5ms)
  Rendered plugins/redmine_issue_evm/app/views/evms/_project_chart_js.html.erb (21.2ms)
  Rendered plugins/redmine_issue_evm/app/views/evms/_version_chart_js.html.erb (0.6ms)
  Rendered plugins/redmine_issue_evm/app/views/evms/_version_chart_js.html.erb (3.5ms)
  Rendered plugins/redmine_issue_evm/app/views/evms/index.html.erb within layouts/base (50.1ms)
Completed 500 Internal Server Error in 1018ms (ActiveRecord: 137.5ms)

ActionView::Template::Error (undefined method `<' for nil:NilClass):
    1: <script>
    2:   var actualWeek = <%= basis_date.to_time.to_i* 1000 %>;
    3:   var graphTitleMain = <%= raw version_name.to_json %> ;
    4:   var versionChartData = <%= raw version_evm.chart_data.to_json %>;
    5:   var verisonChartHtmlElement = "evm-graph-lines-version-" + <%= version %>;
    6:   drawVersionChart(versionChartData, verisonChartHtmlElement, actualWeek, graphTitleMain);
    7: </script>
  plugins/redmine_issue_evm/lib/evm_logic.rb:256:in `chart_data'
  plugins/redmine_issue_evm/app/views/evms/_version_chart_js.html.erb:4:in `_plugins_redmine_issue_evm_app_views_evms__version_                                                           chart_js_html_erb__4010299803168523046_69914177213540'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_                                                           enhancements'
  plugins/redmine_issue_evm/app/views/evms/index.html.erb:110:in `block in _plugins_redmine_issue_evm_app_views_evms_index_html                                                           _erb__1389500978454118078_69914172123540'
  plugins/redmine_issue_evm/app/views/evms/index.html.erb:108:in `each'
  plugins/redmine_issue_evm/app/views/evms/index.html.erb:108:in `_plugins_redmine_issue_evm_app_views_evms_index_html_erb__138                                                           9500978454118078_69914172123540'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:74:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by momibun926** [comment]
@Jiangshan00001 
Thank you for reporting.
There is no version, the graph will be displayed.
I could not reproduce it of my environment.

1.Are you using the latest source?
2.Could you tell me more information about the ISSUE you entry?
