### ISSUE TITLE
PV in basis date value

### ISSUE THREAD

**Issue by Rodrigosalasv** [momibun926/redmine_issue_evm#92]
Hello,

I do not understand why my PV value is not correct in basis date value on my board.
![image](https://user-images.githubusercontent.com/27017278/29293211-8a726232-814a-11e7-8a35-01e10f7c153b.png)

As you can see, my PV value on my board is the same than BAC value.
Is it a bug or a mistake of my part?

Thank you

**Comment by momibun926** [comment]
@Rodrigosalasv 
Thank you for report.
It is a bug.
Please wait until you fix it

**Comment by momibun926** [comment]
@Rodrigosalasv 
I push just now at latest master.
Could you please check if it works?

**Comment by Rodrigosalasv** [comment]
Hello,

Thank you very much.
It works well now, the values are correct.

If you are interested, i can help you with french and spanish translation of plugin.

**Comment by momibun926** [comment]
@Rodrigosalasv 
Thank you for checking.
I really appreciate it.

**Comment by momibun926** [comment]
I am interested.
Please translate it into French and Spanish.

**Comment by Rodrigosalasv** [comment]
Hello,

Sorry for delay.
Please find attached french and spanish translation.
I checked them whith our project managers.

Regards

De : Hajime Nakagama [mailto:notifications@github.com]
Envoyé : mercredi 16 août 2017 14:26
À : momibun926/redmine_issue_evm <redmine_issue_evm@noreply.github.com>
Cc : Rodrigo Salas Vergara <rodrigo.salas-vergara@acrelec.com>; Mention <mention@noreply.github.com>
Objet : Re: [momibun926/redmine_issue_evm] PV in basis date value (#92)


I am interested.
Please translate it into French and Spanish.
