### ISSUE TITLE
ruby 2.5.3 マイグレーションエラー

### ISSUE THREAD

**Issue by yukiafronia** [momibun926/redmine_issue_evm#94]
ruby 2.5.3でマイグレーションエラー　らしきもの出ました。  
対応可能ですか？  
<br>  
![image](https://user-images.githubusercontent.com/23439178/50347274-4eeed480-0578-11e9-8d92-86a5e420f673.png)  
<br>  
コードだと、長くなるので画像で失礼します。

**Comment by momibun926** [comment]
レポートありがとうございます。
パッと見ただけでは分からないのです。少々お待ち頂けますでしょうか？

**Comment by momibun926** [comment]
きっとruby2.5.3では動かない書き方なんだと思います。対応するのには少し時間がかかりそうです。

**Comment by yukiafronia** [comment]
承知です  
redmine 4.0には対応されてるようなので大丈夫かとは思いますがよろしくお願い致します。  
お手数をおかけします。...

**Comment by momibun926** [comment]
ちょっと調べてみました。
私の環境では試していないのですが、以下のファイルを修正することでMigration出来そうな感じです。（12/9に4.0がリリースされていたのですね）

<対象ファイル>
001_create_evmbaselines.rb
002_create_evmbaseline_issues.rb
003_add_column_evmbaselines.rb

<修正箇所>
ActiveRecord::Migration
->
ActiveRecord::Migration[4.2]

migrationファイルの記載方法がRails5で非互換のアップデートが加えられており、Rails4.2以前に記述したものに対しては互換性を保つ為明示的にActiveRecord::Migration[4.2]を継承する必要があるようです。

お手数ですが、上記のファイルを修正していただき、再度migrationを実施していただけますでしょうか？

**Comment by yukiafronia** [comment]
早々の調査ありがとうございます。
上記コード修正して確認致します

**Comment by momibun926** [comment]
redmine4.0上で動作確認してみました。
migrationだけではなく、ちらほらと対応できていない部分がありましたので、修正(#95)してmaterにmergeしました。よろしければ取得してみてください。
何かございましたら、気軽にissueを上げていただけたらと思います。

**Comment by yukiafronia** [comment]
お待たせして申し訳ございません。
修正でmergeされたものですが、マイグレーションは通るみたいですが、マイグレーション後 rebootで反映させようとすると、Redmineの初期画面が出なくなってしまいます。   

マイグレーション時
![image](https://user-images.githubusercontent.com/23439178/50384314-7bd0f200-0706-11e9-930a-7d26c019ba93.png)

Redmine エラー画面(reboot後の画面)
![image](https://user-images.githubusercontent.com/23439178/50384085-d9fbd600-0702-11e9-88c7-859263628b7b.png)

このように、表示されrebootをかけると Redmine のエラー画面になります...

**Comment by momibun926** [comment]
私の環境では動いていたのですが、何か見落とし？があるかもしれません。再度インストールからやり直してみます。
しばらくお待ちください。
あと、可能であれば、ログに出力されている内容を貼っていただけますでしょうか？
お手数をおかけいたしますが、よろしくお願いします。

**Comment by yukiafronia** [comment]
原因が特定できました。
私の環境では、redmineのプラグイン導入時に再起動をかけプラグインを反映させるようにしていましたが再起動なしで正常に稼働することが確認できました。  
ご迷惑おかけしてすみませんでした。

また、ruby 2.5.3への対応とredmine 4.0への対応ありがとうございました。  
<br>  
![image](https://user-images.githubusercontent.com/23439178/50390736-3a7c2900-077e-11e9-9f62-d78639d77549.png)

**Comment by momibun926** [comment]
連絡してありがとうございます。
導入できたようで、安心しました。
もしよろしければ、issueをクローズしていただけたらと思います。
今後、何かございましたら、またissueをあげていただけたらと思います。
これからのカスマイズなどに役立てたいと思いますので、合わせてご要望などもお寄せください。
